export const plateDishes = [
  {
    id: "rice",
    n: "Kerala Matta Rice & Pappadam",
    t: "Center Platter",
    p: "Steaming hot traditional red matta rice served unlimited with a golden crispy pappadam.",
    taste: "Fluffy & wholesome",
    icon: "🍚",
    img: "/hero_thali.jpg",
    x: 50,
    y: 52,
  },
  {
    id: "sambar",
    n: "Kottayam Style Sambar",
    t: "Right Katori",
    p: "Slow-simmered yellow toor dal with fresh drumsticks, shallots, tomato, and freshly ground coriander spice blend.",
    taste: "Tangy & aromatic",
    icon: "🍲",
    img: "/sambar.jpg",
    x: 79,
    y: 39,
  },
  {
    id: "payasam",
    n: "Palada Payasam",
    t: "Top Left",
    p: "Slow-reduced milk payasam with tender rice flakes (ada), ghee-roasted cashews, and golden raisins.",
    taste: "Sweet festive delight",
    icon: "✨",
    img: "/palada_payasam.jpg",
    x: 28,
    y: 33,
  },
  {
    id: "avial",
    n: "Traditional Kerala Avial",
    t: "Top Right",
    p: "Medley of seasonal country vegetables in a coarse coconut, green chili, and cumin gravy topped with raw coconut oil.",
    taste: "Rich coconut flavor",
    icon: "🥗",
    img: "/hero_thali.jpg",
    x: 64,
    y: 27,
  },
  {
    id: "moru",
    n: "Spiced Buttermilk (Sambharam)",
    t: "Top Center",
    p: "Chilled churned yogurt infused with crushed ginger, green chili, and fragrant curry leaves.",
    taste: "Cooling & refreshing",
    icon: "🥛",
    img: "/hero_thali.jpg",
    x: 46,
    y: 22,
  },
  {
    id: "thoran",
    n: "Beans & Coconut Thoran",
    t: "Lower Right",
    p: "Fresh yard-long beans finely chopped and stir-fried with freshly scraped coconut and mustard tempering.",
    taste: "Crunchy & fresh",
    icon: "🌱",
    img: "/hero_thali.jpg",
    x: 81,
    y: 56,
  },
  {
    id: "chips",
    n: "Crispy Upperi & Mango Pickle",
    t: "Bottom Right",
    p: "Fresh coconut oil banana chips, crisp salted green chili, and fiery spicy tender mango pickle.",
    taste: "Crisp & spicy crunch",
    icon: "🍌",
    img: "/hero_thali.jpg",
    x: 68,
    y: 73,
  },
  {
    id: "fishcurry",
    n: "Kudampuli Fish Curry / Roast",
    t: "Bottom Center",
    p: "Signature Kottayam delicacy cooked in clay pots with smoked kudampuli (Malabar tamarind) and shallots.",
    taste: "Smoky, spicy & tangy",
    icon: "🐟",
    img: "/hero_thali.jpg",
    x: 42,
    y: 75,
  },
  {
    id: "rasam",
    n: "Garlic & Pepper Rasam",
    t: "Bottom Left",
    p: "Clear spicy broth brewed with crushed Tellicherry black pepper, garlic, tamarind, and cilantro.",
    taste: "Zesty & digestive",
    icon: "🥣",
    img: "/sambar.jpg",
    x: 23,
    y: 65,
  },
  {
    id: "pachadi",
    n: "Pineapple Pachadi",
    t: "Left Katori",
    p: "Sweet ripe pineapple simmered in yogurt with mustard seed tempering, balancing the spicy curries.",
    taste: "Sweet, tangy & creamy",
    icon: "🍍",
    img: "/hero_thali.jpg",
    x: 19,
    y: 48,
  },
];

export const menu = {
  "Meals & Thali": [
    { n: "Veg Thali", d: "Traditional Kerala meals with rice, sambar, avial, thoran, pachadi, rasam, curd, pappadam & payasam", p: "₹160", img: "/hero_thali.jpg", veg: true, popular: true },
    { n: "Fish Curry Meals", d: "Our special meal accompanied with authentic Kottayam kudampuli fish curry & shallow fry", p: "₹230", img: "/hero_thali.jpg", veg: false, popular: true },
    { n: "Chicken Thali", d: "Special meals served with pepper chicken roast, thick gravy and all traditional sides", p: "₹250", img: "/chicken_dosa.jpg", veg: false },
    { n: "Standard Kerala Meals", d: "All-you-can-eat quick lunch with daily curries and warm payasam", p: "₹140", img: "/hero_thali.jpg", veg: true },
  ],
  "Specialty Dosas": [
    { n: "Crispy Masala Dosa", d: "Thin golden crepe filled with spiced potato masala, served with crispy medu vada & chutneys", p: "₹110", img: "/masala_dosa.jpg", veg: true, popular: true },
    { n: "Special Chicken Dosa", d: "Chef's special crispy dosa stuffed with aromatic shredded chicken sukka masala", p: "₹180", img: "/chicken_dosa.jpg", veg: false, popular: true },
    { n: "Ghee Roast Dosa", d: "Extra crispy cone dosa roasted in pure fragrant desi ghee with 3 varieties of chutneys", p: "₹95", img: "/masala_dosa.jpg", veg: true },
    { n: "Egg Masala Dosa", d: "Layered with beaten country egg, black pepper and spicy onion-tomato masala", p: "₹130", img: "/masala_dosa.jpg", veg: false },
  ],
  "Biryani & Mains": [
    { n: "Malabar Chicken Dum Biryani", d: "Fragrant kaima rice cooked on slow dum with succulent chicken, fried onions, egg & raita", p: "₹220", img: "/chicken_biryani.jpg", veg: false, popular: true },
    { n: "Kerala Beef Roast Plate", d: "Slow-cooked tender beef with coconut slivers, crushed pepper and soft Kerala parottas", p: "₹260", img: "/chicken_biryani.jpg", veg: false },
    { n: "Karimeen / Seer Fish Fry", d: "Fresh catch marinated in traditional red chili masala and shallow fried on tawa", p: "₹240", img: "/hero_thali.jpg", veg: false },
  ],
  "Cafe & Sweets": [
    { n: "Rich Palada Payasam", d: "Our signature dessert made fresh daily with reduced milk, cardamom and ghee-roasted cashews", p: "₹70", img: "/palada_payasam.jpg", veg: true, popular: true },
    { n: "Tender Coconut Pudding (Elaneer)", d: "Chilled, silky smooth delicacy prepared with fresh tender coconut water and pulp", p: "₹90", img: "/palada_payasam.jpg", veg: true },
    { n: "Fresh Fruit Shakes & Juices", d: "Avocado shake, Sharjah shake, freshly pressed seasonal juices and ice creams", p: "₹80", img: "/dining_hall.jpg", veg: true },
  ],
};

export const reviewsData = [
  {
    author: "Rahul Nair",
    rating: 5,
    source: "Google Review",
    time: "Local Guide • 42 reviews",
    quote: "Best Kerala Thali in Kottayam town! The fish curry and unlimited meals on banana leaf taste just like home. Fast service even during busy lunch hours.",
  },
  {
    author: "Deepa Mathew",
    rating: 5,
    source: "Google Review",
    time: "3 months ago",
    quote: "Their Chicken Dosa and Masala Dosa are unbeatable. Perfect spot opposite Malayala Manorama for both quick breakfast and relaxed family dinners.",
  },
  {
    author: "Anil Kumar K",
    rating: 4,
    source: "Google Review",
    time: "Local Guide",
    quote: "Authentic Kerala cuisine, tasty biryani, and the Palada payasam at the end was delicious. Affordable price for such great quality and neat dining hall.",
  },
];
